package com.finance.dashboard.service;
import com.finance.dashboard.model.FinancialRecord;
import com.finance.dashboard.model.enums.Category;
import com.finance.dashboard.model.enums.TransactionType;
import com.finance.dashboard.repository.FinancialRecordRepository;
import com.finance.dashboard.repository.FinancialRecordSpecification;
import com.opencsv.CSVWriter;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.nio.charset.StandardCharsets;
import java.time.LocalDate;
import java.util.List;

@Slf4j @Service @RequiredArgsConstructor
public class ExportService {
    private final FinancialRecordRepository recordRepository;
    private static final String[] HEADERS = {"ID","Type","Category","Amount (INR)","Date","Description","Tags","Auto-Generated","Created By","Created At"};

    @Transactional(readOnly=true)
    public byte[] exportToCsv(TransactionType type, Category category, LocalDate from, LocalDate to, String keyword) throws IOException {
        List<FinancialRecord> records = recordRepository.findAll(
                FinancialRecordSpecification.filter(type,category,from,to,keyword,null,null), Sort.by("date").descending());
        ByteArrayOutputStream raw = new ByteArrayOutputStream();
        raw.write(new byte[]{(byte)0xEF,(byte)0xBB,(byte)0xBF}); // BOM before writer
        try (OutputStreamWriter osw = new OutputStreamWriter(raw, StandardCharsets.UTF_8);
             CSVWriter writer = new CSVWriter(osw)) {
            writer.writeNext(HEADERS);
            for (FinancialRecord r : records) {
                writer.writeNext(new String[]{
                    String.valueOf(r.getId()), r.getType().name(), r.getCategory().name(),
                    r.getAmount().toPlainString(), r.getDate().toString(), nvl(r.getDescription()),
                    nvl(r.getTags()), String.valueOf(r.isAutoGenerated()),
                    r.getCreatedBy()!=null?r.getCreatedBy().getUsername():"",
                    r.getCreatedAt()!=null?r.getCreatedAt().toString():""
                });
            }
            writer.flush();
        }
        log.info("CSV export: {} records", records.size());
        return raw.toByteArray();
    }
    private String nvl(String s){return s!=null?s:"";}
}
