package com.finance.dashboard.scheduler;
import com.finance.dashboard.model.*;
import com.finance.dashboard.model.enums.*;
import com.finance.dashboard.repository.*;
import com.finance.dashboard.service.*;
import com.finance.dashboard.util.RecurringUtils;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;
import java.time.LocalDate;

@Slf4j @Component @RequiredArgsConstructor
public class RecurringTransactionScheduler {
    private final RecurringTransactionRepository recurringRepo;
    private final FinancialRecordRepository recordRepo;
    private final NotificationService notificationService;
    private final BudgetAlertService budgetAlertService;
    private final AuditService auditService;

    @Scheduled(cron="${app.scheduler.recurring-cron:0 0 1 * * *}")
    @Transactional
    public void execute() {
        LocalDate today=LocalDate.now();
        var due=recurringRepo.findAllDueByDate(today);
        log.info("Recurring scheduler: {} rules due",due.size());
        for (RecurringTransaction rt : due) {
            try { post(rt,today); }
            catch(Exception e){log.error("Failed recurring [id={}]: {}",rt.getId(),e.getMessage());}
        }
    }

    private void post(RecurringTransaction rt, LocalDate today) {
        FinancialRecord r=FinancialRecord.builder().type(rt.getType()).category(rt.getCategory())
                .amount(rt.getAmount()).date(today).description("Auto: "+rt.getName())
                .createdBy(rt.getUser()).autoGenerated(true).build();
        recordRepo.save(r);
        rt.setLastExecutedDate(today);
        rt.setNextExecutionDate(RecurringUtils.computeNextDate(today,rt.getFrequency()));
        if(rt.getEndDate()!=null&&rt.getNextExecutionDate().isAfter(rt.getEndDate())){rt.setActive(false);}
        recurringRepo.save(rt);
        notificationService.send(rt.getUser(),NotificationType.RECURRING_EXECUTED,
                String.format("✅ Auto-posted: %s — ₹%.2f",rt.getName(),rt.getAmount()));
        if(rt.getType()==TransactionType.EXPENSE) budgetAlertService.evaluate(rt.getUser(),rt.getCategory(),today);
        auditService.log(AuditAction.RECURRING_EXECUTED,"SYSTEM","RecurringTransaction",rt.getId(),null,null,null,"Auto-posted: "+rt.getName());
    }
}
