package com.finance.dashboard.model.enums;
public enum AuditAction {
    LOGIN_SUCCESS, LOGIN_FAILURE, LOGOUT, TOKEN_REFRESH,
    USER_CREATED, USER_UPDATED, USER_DELETED, USER_ACTIVATED, USER_DEACTIVATED,
    RECORD_CREATED, RECORD_UPDATED, RECORD_DELETED,
    BUDGET_CREATED, BUDGET_UPDATED, BUDGET_DELETED, BUDGET_WARNING, BUDGET_CRITICAL, BUDGET_EXCEEDED,
    RECURRING_CREATED, RECURRING_UPDATED, RECURRING_DELETED, RECURRING_EXECUTED,
    CSV_EXPORTED, NOTIFICATION_READ, PASSWORD_CHANGED
}
