package com.finance.dashboard.model.enums;
public enum Category {
    SALARY, FREELANCE, INVESTMENT, RENTAL, BUSINESS, BONUS, GIFT, OTHER_INCOME,
    FOOD, RENT, UTILITIES, TRANSPORT, HEALTHCARE, EDUCATION, ENTERTAINMENT,
    SHOPPING, TRAVEL, INSURANCE, SAVINGS, EMI, SUBSCRIPTION, PERSONAL_CARE,
    HOME, OTHER_EXPENSE
}
