package com.finance.dashboard.model;
import com.finance.dashboard.model.enums.Category;
import com.finance.dashboard.model.enums.TransactionType;
import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.CreationTimestamp;
import org.hibernate.annotations.UpdateTimestamp;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity @Table(name = "financial_records", indexes = {
    @Index(name = "idx_fr_type", columnList = "type"),
    @Index(name = "idx_fr_category", columnList = "category"),
    @Index(name = "idx_fr_date", columnList = "date"),
    @Index(name = "idx_fr_created_by", columnList = "created_by_id"),
    @Index(name = "idx_fr_deleted", columnList = "deleted")
})
@Getter @Setter @NoArgsConstructor @AllArgsConstructor @Builder
public class FinancialRecord {
    @Id @GeneratedValue(strategy = GenerationType.IDENTITY) private Long id;
    @Enumerated(EnumType.STRING) @Column(nullable = false, length = 20) private TransactionType type;
    @Enumerated(EnumType.STRING) @Column(nullable = false, length = 30) private Category category;
    @Column(nullable = false, precision = 15, scale = 2) private BigDecimal amount;
    @Column(nullable = false) private LocalDate date;
    @Column(length = 500) private String description;
    @Column(length = 300) private String tags;
    @Column(nullable = false) @Builder.Default private boolean deleted = false;
    @Column(nullable = false) @Builder.Default private boolean autoGenerated = false;
    @ManyToOne(fetch = FetchType.LAZY) @JoinColumn(name = "created_by_id", nullable = false) private User createdBy;
    @CreationTimestamp @Column(nullable = false, updatable = false) private LocalDateTime createdAt;
    @UpdateTimestamp private LocalDateTime updatedAt;
}
