package com.finance.dashboard.dto.response;

import com.finance.dashboard.model.enums.TransactionType;
import lombok.Builder;
import lombok.Data;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Data
@Builder
public class FinancialRecordResponse {

    private Long id;

    private TransactionType type;

    private String category;

    private BigDecimal amount;

    private LocalDate date;

    private String description;

    private String tags;

    private boolean autoGenerated;

    private String createdBy;

    private LocalDateTime createdAt;

    private LocalDateTime updatedAt;
}