package com.finance.dashboard.dto.response;
import com.finance.dashboard.model.enums.*;
import lombok.*;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
@Data @Builder
public class FinancialRecordResponse {
    private Long id;
    private TransactionType type;
    private Category category;
    private BigDecimal amount;
    private LocalDate date;
    private String description, tags, createdBy;
    private boolean autoGenerated;
    private LocalDateTime createdAt, updatedAt;
}
